config/routes.rb
Rails.application.routes.draw do
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index"
 
  devise_for :users, :controllers => { :registrations => "users/registrations" } 

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_attached_file :image, style: { thumb: '120x120', large: '300x400' }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]
	def index

		@pins = Pin.all.order("created_at DESC")
	end
	def profile
		@pins = Pin.all.order("created_at DESC")

	end
	def show
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			# Welcome.welcome_user.deliver
			redirect_to @pin, notice: "successfully created"
		else
			render 'new'
		end
	end
	def new
		@pin = current_user.pins.build
	end
	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was Successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end
	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end
	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end
	def find_pin
		@pin = Pin.find(params[:id])
	end
end

app/controllers/users/registrations_controller.rb
module Users
class RegistrationsController < Devise::RegistrationsController
	def create

		 build_resource(sign_up_params)

    resource.save
    # require 'pry'
    # binding.pry
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        Welcome.welcome_user(resource).deliver
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      # set_minimum_password_length
      respond_with resource
    end

		
	end
    # Override the action you want here.
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Pin Board
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= csrf_meta_tags 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
%body
	%nav.navbar.navbar-default
		.container
			
			.navbar-brand= link_to "Pin Board", root_path
			%button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", :type => "button"}
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			- if user_signed_in?
				#myNavbar.collapse.navbar-collapse
					%ul.nav.navbar-nav.navbar-right
						%li= link_to "New Pin", new_pin_path
						%li= link_to "Account", edit_user_registration_path
						%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path
	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert alert-info"

		= yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
		%h2
		= pluralize(@pin.errors.count, "error")
		"prevented this Pin from saving"
		%ul
			- @pin.errors.full_messages.each do |msg|
				%li= msg

	.form-group
		= f.input :image, input_html: { class: 'form-control', style: 'height:auto!important;'}
	.form-group
		= f.input :title, input_html: { class: 'form-control'}

	.form-group
		= f.input :description, input_html: { class: 'form-control'}
		%br/
		= f.button :submit, class:"btn btn-primary"

app/views/pins/_form1.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
		%h2
		= pluralize(@pin.errors.count, "error")
		"prevented this Pin from saving"
		%ul
			- @pin.errors.full_messages.each do |msg|
				%li = msg
		
	.form-group
		=f.input :title, input_html: {class: 'form-control'}
	.form-group
		= f.input :description, input_html:{class: 'form-control'}
		= f.button :submit, class: "btn btn-primary"
		

app/views/pins/edit.html.haml

%h1 Edit Pin

= render 'form'

= link_to "Cancle", pin_path 

app/views/pins/index.html.haml
#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image.url), pin
			.panel-body
				%h2= link_to pin.title, pin
				%p.user
					Submitted By
					= pin.user.email

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 New Pin
			.panel-body

				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @pin.image.url
			.panel-body
				%h1= @pin.title
				%p.description= @pin.description
				%p
				
			.panel-footer
				.row
					.col-md-6
						%p.user
						Submitted by
						= @pin.user.email
					.col-md-6
						.btn-group.pull-right
							=link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
								%span.glyphicon.glyphicon-heart
									= @pin.get_upvotes.size
							- if user_signed_in?
								
								- if current_user.email == @pin.user.email

									=link_to "Edit", edit_pin_path, class: "btn btn-default"
									=link_to "Delete", pin_path, method: :delete, data: { confirm: "Are You Sure??"}, class: "btn btn-default"




app/views/welcome/welcome_user.html.erb
<h1> Hello <%= @user.email %> </h1>
<h3>Welcome to the PinBoard</h3>
	<p>Here you can explore the world of Images.<br/>
		You can upload the images and like the images on clicking the heart button.
<br/><br/>
		<strong>
			Thanks<br/>
			Kind Regards,<br/>
			Mayank Rajput
		</strong>
	</p>